# Generated by Django 2.1.5 on 2019-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkl_category',
            name='short_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkl_dimension',
            name='short_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkl_subcategory',
            name='short_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkl_subsubcategory',
            name='short_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
