# Generated by Django 2.1.5 on 2019-11-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191105_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lkl_subsubcategory',
            old_name='description',
            new_name='description_basic_competence',
        ),
        migrations.AddField(
            model_name='lkl_subsubcategory',
            name='description_beginning',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkl_subsubcategory',
            name='description_in_development',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkl_subsubcategory',
            name='description_professional_competence',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkl_subsubcategory',
            name='description_starter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
