# Generated by Django 2.1.5 on 2019-11-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primary_Skills_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level_A_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_3_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_3_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_3_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='profile_owner',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
