# Generated by Django 2.1.5 on 2019-11-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='primary_skills_profile',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='profile_owner',
        ),
        migrations.DeleteModel(
            name='Primary_Skills_Profile',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
