# Generated by Django 2.1.5 on 2019-11-06 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_auto_20191106_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primary_Skills_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level_A_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_A_3_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_B_3_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('Level_C_3_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='primary_skills_profile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.User_Profile'),
        ),
    ]
