# Generated by Django 2.1.5 on 2019-11-06 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20191106_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
