# Generated by Django 2.1.5 on 2019-11-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20191106_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_A_1_1',
            new_name='level_A_1_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_A_1_2',
            new_name='level_A_1_2',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_A_2_1',
            new_name='level_A_2_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_A_2_2',
            new_name='level_A_2_2',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_A_3_1',
            new_name='level_A_3_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_A_3_2',
            new_name='level_A_3_2',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_B_1_1',
            new_name='level_B_1_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_B_1_2',
            new_name='level_B_1_2',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_B_2_1',
            new_name='level_B_2_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_B_2_2',
            new_name='level_B_2_2',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_B_3_1',
            new_name='level_B_3_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_B_3_2',
            new_name='level_B_3_2',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_C_1_1',
            new_name='level_C_1_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_C_1_2',
            new_name='level_C_1_2',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_C_2_1',
            new_name='level_C_2_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_C_2_2',
            new_name='level_C_2_2',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_C_3_1',
            new_name='level_C_3_1',
        ),
        migrations.RenameField(
            model_name='primary_skills_profile',
            old_name='Level_C_3_2',
            new_name='level_C_3_2',
        ),
    ]
