# Generated by Django 2.1.5 on 2019-11-12 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20191108_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='LKL_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=500)),
                ('resource_URL', models.URLField()),
                ('categories', models.ManyToManyField(to='webapp.LKL_Subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='studentId',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_shared_list',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Docent'}, related_name='accessable_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
