# Generated by Django 2.1.5 on 2019-11-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20191112_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='studentId',
            new_name='student_id',
        ),
    ]
