# Generated by Django 2.1.5 on 2019-11-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20191112_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broad_Professional_Basis_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_D_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_D_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_D_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_D_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_D_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_D_3_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_E_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_E_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_E_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_E_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_E_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_E_3_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_F_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_F_1_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_F_2_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_F_2_2', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_F_3_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('level_G_1_1', models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.User_Profile')),
            ],
        ),
    ]
