# Generated by Django 2.1.5 on 2019-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_broad_professional_basis_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='broad_professional_basis_profile',
            name='level_G_1_2',
            field=models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='broad_professional_basis_profile',
            name='level_G_2_1',
            field=models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='broad_professional_basis_profile',
            name='level_G_2_2',
            field=models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='broad_professional_basis_profile',
            name='level_G_3_1',
            field=models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='broad_professional_basis_profile',
            name='level_G_3_2',
            field=models.CharField(choices=[('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='B', max_length=2),
        ),
    ]
