# Generated by Django 2.1.5 on 2019-11-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20191114_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_Identity_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_q1', models.TextField()),
                ('answer_q2', models.TextField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.User_Profile')),
            ],
        ),
    ]
