# Generated by Django 2.1.5 on 2019-11-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_professional_identity_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_identity_profile',
            name='answer_q1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='professional_identity_profile',
            name='answer_q2',
            field=models.TextField(blank=True),
        ),
    ]
