# Generated by Django 2.1.5 on 2019-11-20 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20191119_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_shared_list',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Docent'}, related_name='accessable_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
