# Generated by Django 2.1.5 on 2019-11-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20191120_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_D_1_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_D_1_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_D_2_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_D_2_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_D_3_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_D_3_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_E_1_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_E_1_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_E_2_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_E_2_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_E_3_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_E_3_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_F_1_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_F_1_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_F_2_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_F_2_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_F_3_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_G_1_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_G_1_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_G_2_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_G_2_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_G_3_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='broad_professional_basis_profile',
            name='level_G_3_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_A_1_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_A_1_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_A_2_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_A_2_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_A_3_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_A_3_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_B_1_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_B_1_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_B_2_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_B_2_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_B_3_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_B_3_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_C_1_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_C_1_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_C_2_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_C_2_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_C_3_1',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='primary_skills_profile',
            name='level_C_3_2',
            field=models.CharField(choices=[('N', 'Geen niveau'), ('B', 'Beginnend'), ('IO', 'In Ontwikkeling'), ('S', 'Startbekwaam'), ('BC', 'Basisbekwaam'), ('PC', 'Vakbekwaam')], default='N', max_length=2),
        ),
    ]
