# Generated by Django 2.1.5 on 2019-11-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_lkl_resource_hva_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_a_note', models.TextField(blank=True)),
                ('cat_b_note', models.TextField(blank=True)),
                ('cat_c_note', models.TextField(blank=True)),
                ('cat_d_note', models.TextField(blank=True)),
                ('cat_e_note', models.TextField(blank=True)),
                ('cat_f_note', models.TextField(blank=True)),
                ('cat_g_note', models.TextField(blank=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.User_Profile')),
            ],
        ),
    ]
